apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-networking-deployment
spec:
  selector:
    matchLabels:
      app: authentication-app
      tier: backend
  template:
    metadata:
      labels:
        app: authentication-app
        tier: backend
    spec:
      containers:
        - name: auth
          image: sunshineaact/k8s-networking-auth
