apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-second-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-app
      tier: backend
  template:
    metadata:
      labels:
        app: first-app
        tier: backend
    spec:
      containers:
        - name: k8s-first-app
          image: sunshineaact/k8s-first-app
          imagePullPolicy: Always
