apiVersion: v1
kind: Service
metadata:
  name: k8s-networking-service
spec:
  selector:
    app: authentication-app
    tier: backend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
