apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-app
  template:
    metadata:
      labels:
        app: authentication-app
    spec:
      containers:
        - name: auth
          image: sunshineaact/k8s-networking-auth
        - name: users
          image: sunshineaact/k8s-networking-users
