apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-folder
spec:
  accessModes:
    - "ReadWriteOnce"
  capacity:
    storage: 1G
  hostPath:
    path: /data
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-folder-claim
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: standard
  resources:
    requests:
      storage: 1G
  volumeName: users-folder
